### ISSUE TITLE
Cronjob management from GUI

### ISSUE THREAD

**Issue by pihome-shc** [pihome-shc/PiHomeHVAC#34]
i think worth working on this issue. 
https://github.com/pihome-shc/pihome/issues/327
@sandreialexandru gave some good suggestions.

**Comment by twa127** [comment]
Hi,

building on @sandreialexandru code, so that the list of jobs gets build from the table, rather than hardcoded, changed jobs table column 'name' to 'job_name'  -

# Schedule Library imported
import schedule
import time
import os
import configparser
import MySQLdb as mdb

# Initialise the database access variables
config = configparser.ConfigParser()
config.read("/var/www/st_inc/db_config.ini")
dbhost = config.get("db", "hostname")
dbuser = config.get("db", "dbusername")
dbpass = config.get("db", "dbpassword")
dbname = config.get("db", "dbname")

con = mdb.connect(dbhost, dbuser, dbpass, dbname)
cur = con.cursor()

# Build functions based on entries in table
def func_builder(name):
    def f():
        action = os.popen(row[1] + " \n")
        action_output = action.read()
        print(action_output)
        cur.execute(
            "UPDATE `jobs` SET `output` = %s WHERE `job_name` = %s",
            (action_output, name),
        )
        con.commit()
        return name

    return f


# Clear any existing schedules
schedule.clear()

# Build the new schedules
cur.execute("SELECT `job_name`, `script`, `time` FROM `jobs`")
for row in cur:
    func_builder(row[0])()
    schedule.every(row[2]).minutes.do(func_builder(row[0]))

while True:

    # Checks whether a scheduled task
    # is pending to run or not

    schedule.run_pending()
    time.sleep(1)

**Comment by twa127** [comment]
Suggest that the python script is installed as a service and can be monitored by the existing services GUI

Adding new scheduled tasks or modifying run times is simply and addition or update to the table and a service restart, would need a new GUI in settings to support the new jobs table.

**Comment by pihome-shc** [comment]
question: user who install MaxAir with setup.php gets pip3 install schedule or user needs to install this ?

**Comment by twa127** [comment]
If not already installed, then setup.php will install it automatically

________________________________

**Comment by pihome-shc** [comment]
what else i need to do to make this work? also i see only script location in settings but nothing about program location i.e if i m running php script i need to specify php install location or that is hard coded? 
/usr/bin/php /var/www/cron/weather_update.php

**Comment by twa127** [comment]
Hi,

You specify the script eg /var/www/cron/weather_update.php and the code extracts whatever comes after the '.' character eg php or sh, it then uses this to determine what program to use /usr/bin/php or /usr/bin/bash

**Comment by pihome-shc** [comment]
suggestion: can we add checkbox to enable cronjob in settings, this way we can add our default jobs but have them disabled and user can enable as required.

**Comment by twa127** [comment]
Implemented #63 Initial setup will install the jobs but leave them disabled

**Comment by twa127** [comment]
oops forgot to update the jobs table, icluded in #64

**Comment by twa127** [comment]
I think this can now be closed

**Comment by pihome-shc** [comment]
can we put link to last run status to show it in notepad or something? this would help for any potential troubleshooting

**Comment by twa127** [comment]
Add display last logs as #72

**Comment by pihome-shc** [comment]
no further action required, closing this ticket.
