### ISSUE TITLE
Bug-Missing e-mail address!!! 

### ISSUE THREAD

**Issue by pihome-shc** [pihome-shc/PiHomeHVAC#42]
Issue with email is still there, i think something is not working with model, may be best to have page to redirect user? 

https://github.com/pihome-shc/pihome/issues/440

**Comment by twa127** [comment]
Still not fixed, looks like the issue is related to $_SESSION['user_id'] not getting set properly, then the check in footer.php fails because it has no valid $user_id when checking the table user. Leading on from this, as far as I can see, there is no way to add new users, but you can delete the one existing user.

**Comment by twa127** [comment]
Latest change appears to have fixed the problem, I've committed the same update to pihome

Please let me know if you still experience issues

**Comment by pihome-shc** [comment]
this issue is fixed now.
